// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://denojnsdwhtlilmgmyeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbm9qbnNkd2h0bGlsbWdteWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODMzOTUsImV4cCI6MjA2Njg1OTM5NX0.8aYOITIX8yOsDku27HnUB3Nda1ARL6t1sR0mPp-MeRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});